CREATE TABLE public.cyber_violence_reports (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    violence_type text,
    description text,
    platform text,
    severity text,
    additional_details text,
    status text
);

ALTER TABLE public.cyber_violence_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cyber_violence_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cyber_violence_reports
    ADD CONSTRAINT cyber_violence_reports_pkey PRIMARY KEY (id);

-- Enable Row Level Security
ALTER TABLE public.cyber_violence_reports ENABLE ROW LEVEL SECURITY;

-- Create policy for anonymous inserts
CREATE POLICY "Allow anonymous inserts" ON public.cyber_violence_reports FOR INSERT WITH CHECK (true);
