-- Create the posts table
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    content TEXT,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    author_id UUID REFERENCES auth.users(id)
);

-- Create a policy to allow users to manage their own posts
CREATE POLICY "Allow users to manage their own posts" ON public.posts
    FOR ALL
    USING (auth.uid() = author_id);

-- Create a policy to allow public read access to published posts
CREATE POLICY "Allow public read access to published posts" ON public.posts
    FOR SELECT
    USING (status = 'published');
