-- Add blog engagement features: views, likes, and comments

-- Add views count to posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS views_count BIGINT DEFAULT 0;

-- Create post likes table
CREATE TABLE IF NOT EXISTS post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(post_id, user_id) -- Prevent duplicate likes
);

-- Create post comments table
CREATE TABLE IF NOT EXISTS post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES post_comments(id) ON DELETE CASCADE, -- For threaded comments
    content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'published', -- published, hidden, deleted
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS on new tables
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;

-- Create policies for post_likes
CREATE POLICY "Users can view all likes" ON post_likes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own likes" ON post_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own likes" ON post_likes FOR DELETE USING (auth.uid() = user_id);

-- Create policies for post_comments
CREATE POLICY "Users can view published comments" ON post_comments FOR SELECT USING (status = 'published');
CREATE POLICY "Users can insert their own comments" ON post_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own comments" ON post_comments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON post_comments FOR DELETE USING (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_post_likes_post_id ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_user_id ON post_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_post_id ON post_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_user_id ON post_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_parent_id ON post_comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_status ON post_comments(status);

-- Create function to increment post views
CREATE OR REPLACE FUNCTION increment_post_views(post_uuid UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE posts 
    SET views_count = views_count + 1 
    WHERE id = post_uuid;
END;
$$ LANGUAGE plpgsql;

-- Create function to get post engagement stats
CREATE OR REPLACE FUNCTION get_post_engagement_stats(post_uuid UUID)
RETURNS TABLE (
    views_count BIGINT,
    likes_count BIGINT,
    comments_count BIGINT,
    user_liked BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.views_count,
        COALESCE(l.likes_count, 0),
        COALESCE(c.comments_count, 0),
        EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = post_uuid AND pl.user_id = auth.uid())
    FROM posts p
    LEFT JOIN (
        SELECT post_id, COUNT(*) as likes_count
        FROM post_likes
        GROUP BY post_id
    ) l ON l.post_id = p.id
    LEFT JOIN (
        SELECT post_id, COUNT(*) as comments_count
        FROM post_comments
        WHERE status = 'published'
        GROUP BY post_id
    ) c ON c.post_id = p.id
    WHERE p.id = post_uuid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;